repository:
  name: ms-celulares-homologados-anatel
  description: ðŸ“´ Microservice de consulta a base de dados de celulares homologados pela Anatel.
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: false
